import type { StarterVerse } from "./starterVerses";

/**
 * The full archive of weekly verses Malachi Daily curated during its Baserow
 * era (2023-2026), in the order they were featured. Offered as a one-tap import
 * so people who memorized along week to week do not lose that history when the
 * app moved to a personal, localStorage-only collection.
 *
 * Generated from the Baserow CSV export; duplicates collapsed by reference.
 * Like the starters, only the reference lives here — the text is fetched from
 * bolls.life on import, so nothing in this list needs maintaining. `bookName`
 * matches books.ts exactly so ids and references resolve.
 */
export const legacyVerses: StarterVerse[] = [
  { bookName: "Matthew", chapter: 4, startVerse: 4 },
  { bookName: "Genesis", chapter: 3, startVerse: 8 },
  { bookName: "Exodus", chapter: 29, startVerse: 45, endVerse: 46 },
  { bookName: "John", chapter: 1, startVerse: 14 },
  { bookName: "Revelation", chapter: 21, startVerse: 3 },
  { bookName: "Philippians", chapter: 2, startVerse: 3, endVerse: 4 },
  { bookName: "Psalms", chapter: 37, startVerse: 4, endVerse: 5 },
  { bookName: "Joshua", chapter: 1, startVerse: 9 },
  { bookName: "Romans", chapter: 12, startVerse: 2 },
  { bookName: "Colossians", chapter: 3, startVerse: 17 },
  { bookName: "Proverbs", chapter: 18, startVerse: 2 },
  { bookName: "Philippians", chapter: 3, startVerse: 8 },
  { bookName: "Matthew", chapter: 11, startVerse: 28, endVerse: 29 },
  { bookName: "Psalms", chapter: 150, startVerse: 6 },
  { bookName: "Deuteronomy", chapter: 6, startVerse: 7 },
  { bookName: "John", chapter: 15, startVerse: 5 },
  { bookName: "Psalms", chapter: 63, startVerse: 1 },
  { bookName: "Isaiah", chapter: 43, startVerse: 2 },
  { bookName: "2 Corinthians", chapter: 5, startVerse: 17 },
  { bookName: "Romans", chapter: 6, startVerse: 6 },
  { bookName: "James", chapter: 1, startVerse: 2, endVerse: 3 },
  { bookName: "Hebrews", chapter: 4, startVerse: 12 },
  { bookName: "Psalms", chapter: 73, startVerse: 26 },
  { bookName: "Colossians", chapter: 3, startVerse: 1 },
  { bookName: "Ephesians", chapter: 4, startVerse: 1 },
  { bookName: "Psalms", chapter: 102, startVerse: 18 },
  { bookName: "1 Timothy", chapter: 4, startVerse: 12 },
  { bookName: "Proverbs", chapter: 16, startVerse: 32 },
  { bookName: "Mark", chapter: 8, startVerse: 35 },
  { bookName: "Hebrews", chapter: 12, startVerse: 11 },
  { bookName: "Psalms", chapter: 16, startVerse: 11 },
  { bookName: "Ecclesiastes", chapter: 12, startVerse: 13 },
  { bookName: "Colossians", chapter: 1, startVerse: 19, endVerse: 20 },
  { bookName: "Deuteronomy", chapter: 6, startVerse: 4, endVerse: 5 },
  { bookName: "Matthew", chapter: 28, startVerse: 19, endVerse: 20 },
  { bookName: "Psalms", chapter: 1, startVerse: 1, endVerse: 2 },
  { bookName: "2 Timothy", chapter: 3, startVerse: 16, endVerse: 17 },
  { bookName: "Isaiah", chapter: 7, startVerse: 14 },
  { bookName: "2 Peter", chapter: 1, startVerse: 5, endVerse: 7 },
  { bookName: "Ephesians", chapter: 4, startVerse: 26, endVerse: 27 },
  { bookName: "Joel", chapter: 2, startVerse: 12 },
  { bookName: "Jeremiah", chapter: 29, startVerse: 11 },
  { bookName: "Matthew", chapter: 13, startVerse: 45, endVerse: 46 },
  { bookName: "Romans", chapter: 8, startVerse: 28 },
  { bookName: "Psalms", chapter: 86, startVerse: 11 },
  { bookName: "1 Corinthians", chapter: 6, startVerse: 12 },
  { bookName: "Acts", chapter: 4, startVerse: 12 },
  { bookName: "Matthew", chapter: 13, startVerse: 44 },
  { bookName: "Isaiah", chapter: 53, startVerse: 6 },
  { bookName: "1 Samuel", chapter: 12, startVerse: 21 },
  { bookName: "Mark", chapter: 10, startVerse: 15 },
  { bookName: "1 Samuel", chapter: 15, startVerse: 22 },
  { bookName: "Micah", chapter: 6, startVerse: 8 },
  { bookName: "Galatians", chapter: 2, startVerse: 20 },
  { bookName: "Proverbs", chapter: 13, startVerse: 22 },
  { bookName: "Colossians", chapter: 1, startVerse: 9 },
  { bookName: "Daniel", chapter: 3, startVerse: 17 },
  { bookName: "1 Peter", chapter: 4, startVerse: 9, endVerse: 10 },
  { bookName: "Esther", chapter: 4, startVerse: 14 },
  { bookName: "Job", chapter: 1, startVerse: 21 },
  { bookName: "John", chapter: 4, startVerse: 34 },
  { bookName: "Matthew", chapter: 9, startVerse: 37, endVerse: 38 },
  { bookName: "Luke", chapter: 2, startVerse: 10, endVerse: 11 },
  { bookName: "Zechariah", chapter: 4, startVerse: 6 },
  { bookName: "Numbers", chapter: 23, startVerse: 19 },
  { bookName: "1 Thessalonians", chapter: 5, startVerse: 9 },
  { bookName: "Proverbs", chapter: 18, startVerse: 10 },
  { bookName: "1 Corinthians", chapter: 10, startVerse: 31 },
  { bookName: "Leviticus", chapter: 19, startVerse: 18 },
  { bookName: "Romans", chapter: 12, startVerse: 12 },
  { bookName: "James", chapter: 1, startVerse: 27 },
  { bookName: "Proverbs", chapter: 31, startVerse: 30 },
  { bookName: "John", chapter: 10, startVerse: 10 },
  { bookName: "Lamentations", chapter: 3, startVerse: 22, endVerse: 23 },
  { bookName: "Psalms", chapter: 103, startVerse: 13 },
  { bookName: "James", chapter: 1, startVerse: 19, endVerse: 20 },
];
